// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EstrelaNegra.API.Models
{
    [Table("EQUINE")]
    public partial class Equine
    {
        public Equine()
        {
            EquineGrowth = new HashSet<EquineGrowth>();
            EquineHlthFlwup = new HashSet<EquineHlthFlwup>();
        }

        [Key]
        [Column("HORSE_ID")]
        public int HorseId { get; set; }
        [Column("HORSE_NAME")]
        [StringLength(512)]        
        public string HorseName { get; set; }
        [Column("SUFIXX")]
        [StringLength(512)]        
        public string Sufixx { get; set; }
        [Column("SCORE_GEN")]
        public int? ScoreGen { get; set; }
        [Column("SEX")]
        [StringLength(1)]        
        public string Sex { get; set; }
        [Column("BIRTH", TypeName = "datetime")]
        public DateTime? Birth { get; set; }
        [Column("AGE_DMY")]
        [StringLength(30)]
        public string AgeDmy { get; set; }
        [Column("AGE_MONTH")]
        public int? AgeMonth { get; set; }
        [Column("LIVE")]
        public bool? Live { get; set; }
        [Column("OWN")]
        public bool? Own { get; set; }
        [Column("COAT_COLOR")]
        [StringLength(512)]
        public string CoatColor { get; set; }
        [Column("BREEDER")]
        [StringLength(512)]
        public string Breeder { get; set; }
        [Column("ACTL_OWNER")]
        [StringLength(512)]
        public string ActlOwner { get; set; }
        [Column("FATHER_ID")]
        public int? FatherId { get; set; }
        [Column("MOTHER_ID")]
        public int? MotherId { get; set; }

        [InverseProperty("Horse")]
        public virtual ICollection<EquineGrowth> EquineGrowth { get; set; }
        [InverseProperty("Horse")]
        public virtual ICollection<EquineHlthFlwup> EquineHlthFlwup { get; set; }
    }
}