// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace EstrelaNegra.API.Models
{
    public partial class HENContext : DbContext
    {
        public HENContext()
        {
        }

        public HENContext(DbContextOptions<HENContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Equine> Equine { get; set; }
        public virtual DbSet<EquineGrowth> EquineGrowth { get; set; }
        public virtual DbSet<EquineHlthFlwup> EquineHlthFlwup { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Equine>(entity =>
            {
                entity.HasKey(e => e.HorseId)
                    .HasName("PK__EQUINE__65DCC071831B3EA6");

                entity.Property(e => e.ActlOwner).IsFixedLength();

                entity.Property(e => e.AgeDmy).IsFixedLength();

                entity.Property(e => e.Breeder).IsFixedLength();

                entity.Property(e => e.CoatColor).IsFixedLength();
            });

            modelBuilder.Entity<EquineGrowth>(entity =>
            {
                entity.HasOne(d => d.Horse)
                    .WithMany(p => p.EquineGrowth)
                    .HasForeignKey(d => d.HorseId)
                    .HasConstraintName("FK__EQUINE_GR__HORSE__398D8EEE");
            });

            modelBuilder.Entity<EquineHlthFlwup>(entity =>
            {
                entity.HasOne(d => d.Horse)
                    .WithMany(p => p.EquineHlthFlwup)
                    .HasForeignKey(d => d.HorseId)
                    .HasConstraintName("FK__EQUINE_HL__HORSE__3C69FB99");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}